services:
  auto:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
  comfy:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    volumes:
      - ./data/models:/stable-diffusion/models
      - ./data/models/CLIPEncoder:/stable-diffusion/models/text_encoders
